#!/usr/bin/env groovy

import com.kingsoft.shiyou.pirates.Patching

patching = new Patching(this)

def getWorkspace() {
    def gitBranchName = env.BRANCH_NAME ?: 'master'
    def workspace = gitBranchName == 'master' ? 'master' : getAppVersion.getReleaseVersion()
    return "/home/pirates/jenkins/workspace/Personal_Client_android/${workspace}"
}

pipeline{
    agent {
        node {
            label "pirates:android"
            customWorkspace getWorkspace()
        }
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15'
        ))
        ansiColor('xterm')
    }
    stages {
        stage('Clean') {
            steps {
                cleanWs()
            }
        }
        stage('Upload Debug Symbol') {
            steps {
                script {
                    def amap = [
                        'something': 'my datas',
                        'size': 3,
                        'isEmpty': false
                    ]
                    writeYaml file: 'datas.yaml', data: amap
                    build 'Personal/taoshuang/pirates-client-detach-test/upload-debug-symbol', parameters: patching.mapToBuildParameters([
                        'TARGET_PLATFORM': 'android',
                        'BRANCH_NAME': env.BRANCH_NAME ?: 'master'
                    ]), wait: false
                }
            }
        }
    }
}
