aws:
  s3:
    bucket:
      client:
        name: pirates-dev
        prefix: client/
      server:
        name: pirates-dev
        prefix: server/artifact/
  autoscaling:
    dungeon:
      enabled: true

nomad:
  addr: https://nomad.example.com
  token: pirates-dev.nomad
