aws:
  s3:
    bucket:
      client:
        name: pirates-dev
        prefix: client/
      server:
        name: pirates-dev
        prefix: server/artifact/
  autoscaling:
    dungeon:
      enabled: true

levant:
  deploy:
    approve:
      enable: true
    approvers: 'a, b, c, d, e, f'

nomad:
  addr: https://nomad.example.com
  token: pirates-dev.nomad
