pipeline{
    agent {
        label 'os:linux'
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15'
        ))
        ansiColor('xterm')
    }
    stages {
        stage('Nothing'){
            steps {
                echo "========Do nothing========"
            }
        }
    }
}
