#!/usr/bin/env groovy

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15'
        ))
        ansiColor('xterm')
    }
    stages {
        stage('Nothing') {
            steps {
                echo "========Do nothing========"
            }
        }
    }
    post {
        always {
            feishuNotify what: "Success", withDuration: true, withSummary: true, withChanges: true
        }
    }
}
