#!/usr/bin/env groovy

def getPlatforms() {
    return ['android', 'ios'].join('\n')
}

def getWorkspace(platform) {
    def gitBranchName = params.BRANCH_NAME ?: 'master'
    def workspace = gitBranchName == 'master' ? 'master' : getAppVersion.getReleaseVersion()
    return platform == 'android' ? "/home/pirates/jenkins/workspace/Personal_Client_android/${workspace}" : 
        "/Users/pirates/jenkins/workspace/Personal_Client_ios/${workspace}"
}

pipeline{
    agent {
        node {
            label params.NODE_NAME
            customWorkspace getWorkspace(params.TARGET_PLATFORM)
        }
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15'
        ))
        ansiColor('xterm')
    }
    parameters {
        string(name: 'NODE_NAME',
            defaultValue: '',
            description: 'Builder node name which builds the client, examples: linux-4, mac-3.')
        choice(name: 'TARGET_PLATFORM',
            choices: getPlatforms(),
            description: 'Platform. Android or iOS.')
        string(name: 'BRANCH_NAME',
            defaultValue: '')
    }
    stages {
        stage('Sleep to Wait') {
            steps {
                sh 'sleep 10'
            }
        }
        stage('Upload Debug Symbol') {
            steps {
                script {
                    def datas = readYaml file: 'datas.yaml'
                    assert datas.something == 'my datas'
                    assert datas.size == 3
                    assert datas.isEmpty == false

                    println env.NODE_NAME
                }
            }
        }
    }
}
