#!/usr/bin/env groovy

def getArtifactName() {
    return 'Sublevel_A.zip'
}

def getJobName(String branch = env.BRANCH_NAME) {
    def branchName = branch ?: 'master'
    return "Pirates/Tools/map-automation/${branchName}"
}

//todo: Add check version feature.
def copyAndUnzipArtifact(String mapPath, String branch) {
    def jobName = getJobName(branch)
    echo jobName
}

def copyArtifactFromMapAutomation(String mapPath, String branch = env.BRANCH_NAME) {
    copyAndUnzipArtifact(mapPath, branch)
}

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
                daysToKeepStr: '15',
                artifactNumToKeepStr: '20'
        ))
        ansiColor('xterm')
    }
    stages {
        stage('Project') {
            steps {
                echo dailyPollSCMSchedule('Pirates')
            }
        }
        stage('Build Engine') {
            steps {
                copyArtifactFromMapAutomation 'src/Content/Maps/LV_FFA_Island/Sublevel_A'
            }
        }
    }
}
